### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by puiseux** [mozman/dxfgrabber#1]
I had to make a few changes.

- **tags.py**:

 `from io import StringIO` => `from StringIO import StringIO`

- **\_\_init\_\_.py**:

 `import io` => `import _io as io`

Now it works. 
Sorry but I don't have error messages from previous version...

Cheers

**Comment by mozman** [comment]
What was the problem? dxfgrabber works with Python 2.7, Python 3 and pypy, everything else is not supported.

**Comment by puiseux** [comment]
the problem was on windows 7, python2.7, during `import dxfgrabber`...
I  have no more information, sorry.

**Comment by mozman** [comment]
Problem not reproducible
