### ISSUE TITLE
3DSolid points

### ISSUE THREAD

**Issue by KeisukeYamashita** [mozman/dxfgrabber#10]
How can I get points of 3DSolid?

**Comment by mozman** [comment]
No chance by dxfgrabber or ezdxf! Most Autodesk (DXF/DWG) 3D objects are [SAT](https://en.wikipedia.org/wiki/ACIS) objects, and all you get is the source code of the [SAT](https://en.wikipedia.org/wiki/ACIS) data.

**Comment by KeisukeYamashita** [comment]
Thank you so much for your kind response!
