### ISSUE TITLE
Cannot handle multiple blocks with the same name

### ISSUE THREAD

**Issue by goatchurchprime** [mozman/dxfgrabber#11]
I don't know if this is standard DXF (what on earth is?) but I got this DXF file output from Valentina which uses 3 dxfInserts referencing 3 blocks that are all given the same name.  Here is the file: [valentina_sock.dxf.zip](https://github.com/mozman/dxfgrabber/files/1594683/valentina_sock.dxf.zip)

```Python
import dxfgrabber
d = dxfgrabber.readfile("valentina_sock.dxf")
print([b.name  for b in d.blocks])
print([(e.dxftype, e.name)  for e in d.entities])
>>> ['*Model_Space', '*Paper_Space', 'Detail']
>>> [('INSERT', 'Detail'), ('INSERT', 'Detail'), ('INSERT', 'Detail')]
```

LibreCAD somehow deals with the problem and gives me the 3 pieces, but dxfgrabber.BlocksSection overwrites blocks with the same name.  

Maybe BlocksSection._blocks should actually be a list rather than a dict.

**Comment by mozman** [comment]
Therefor you have to understand BLOCKS:

Blocks are reusable elements, you can see it as container for other DXF entities which can be placed multiply times on different places. But instead of inserting the DXF entities of the block several times just a block reference is placed.

`d.blocks` contains the block definition, accessable by the block name, which is unique in a drawing and therefor a dict is the perfect data structure.

`d.entities` contains all DXF entities of the model space and the actual paper space. The INSERT entity is a block reference, which tells the CAD engine (application) where to place the referenced block, at which scaling and at which rotation. They can also have attached ATTRIB entities, which are individual for each block reference.

And block definitions can also contain block references, which enables block nesting.

**Comment by goatchurchprime** [comment]
Please refer to the example which I attached: [valentina_sock.dxf.zip](https://github.com/mozman/dxfgrabber/files/1594683/valentina_sock.dxf.zip)

This contains 3 blocks, each of which has the same name "Detail", and therefore this line in the library causes all but 2 of them to be over-written on loading:
    https://github.com/mozman/dxfgrabber/blob/master/dxfgrabber/blockssection.py#L40

The file also contains 3 INSERT entities which each ask for the block named "Detail" to be inserted.  

The intent (which I know from the file which wrote it) is for the three different blocks to be placed.  

This intent is successfully interpreted by LibreCAD (you can load the above file and see the 3 different shapes, not one shape over-written 3 times).

Unless blocksection.py line 40 is changed to be self._blocks.append(block) so that multiple blocks of the same name are not over-written, it will be impossible to interpret this intent by using this library.  

This would be a reasonable change to make as the process of looking up from INSERT entities to the block definitions is done outside of the library, and in this case it is a mistake to require the lookup to be done only via the block.name as these are not unique.

At the bare minimum, if this change is not made, there should be a warning that block elements are being lost during the loading process so that nobody has to waste time chasing up this problem again, they can be warned of it right away.

**Comment by mozman** [comment]
AutoCAD does not open your file:

Skipping duplicate definition of Detail in BLOCK_RECORD TableSkipping duplicate definition of Detail in BLOCK_RECORD TableBad handle 41: already in useExpected BLOCK, found LWPOLYLINE on line 2950.

The DXF standard can not distinguish two block definitions with the same name, the block name has to be UNIQUE.

**Comment by goatchurchprime** [comment]
So... AutoCAD gives an error.  Maybe that's an argument that dxfgrabber should give an error too...

I've filed a ticket back to the system that created the problem file.  
https://bitbucket.org/dismine/valentina/issues/791/automatically-give-workpiece-details

It also appears that LibreCAD deletes previously seen blocks:
https://github.com/LibreCAD/LibreCAD/blob/f1372407b9989e19cd9f3b32f8b4a11e4ba770ef/librecad/src/lib/engine/rs_blocklist.cpp#L90
I'm not sure what's how it's reading geometry from my file, but I'll tell them they should throw an error too.
