### ISSUE TITLE
R14 import

### ISSUE THREAD

**Issue by PhilipHB** [mozman/dxfgrabber#15]
Are there plans to teach dxfgrabber R14, or is this out of the scope of maintenance and bugfixes?
I'm asking, because newer Inkscape versions can only export to R14.

**Comment by mozman** [comment]
If you need R14 support look at [ezdxf](github.com/mozman/ezdxf), the package has a different API, but it also has R13/R14 support (by upgrading to R2000) and a brighter future than dxfgrabber.

**Comment by PhilipHB** [comment]
The "brighter future" part convinced me.
