### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by boukeas** [mozman/dxfgrabber#16]
Thank you for making dxfgrabber! A question: does dxfgrabber support additional "inserted" fields? For example, a 3dpolyline can have fields like ObjectName and Material inserted in AutoCAD. These are not visible in the entity's \_\_dict\_\_.

**Comment by mozman** [comment]
Hi!

This are not properties of the DXF entity POLYLINE, this are additional DXF entities linked to the POLYLINE. But there is no Documentation in the DXF reference how AutoCAD or any other CAD application uses the DXF entities to implement such extended features.

**Comment by boukeas** [comment]
I was also unable to find relevant documentation. 

In my working example, these additional fields _do_ "come through" in the dxfgrabber output as MTEXT entities. I am wondering whether I can somehow establish how these MTEXT entities can be _associated_ with the POLYLINE entities they are linked to.

**Comment by mozman** [comment]
I would also recommend to switch to ezdxf, because dxfgrabber will not get new features.

ezdxf supports more DXF entities and has also a pretty printer, which makes reverse engineering much easier: dxfpp -o <filename.dxf> opens a html file in your standard browser.

**Comment by boukeas** [comment]
OK, thanks. I will check ezdxf out.
