### ISSUE TITLE
Pickle Safe

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mozman/dxfgrabber#7]
Hi Manfred. I've tried pickling your dxfgrabber.drawing.Drawing object and it seems to work fine. Have you ever had issues with this or should I consider this safe?
Thanks

**Comment by mozman** [comment]
Hi, never tested or tried this, but he Drawing object contains all the information (as pure Python objects) and no global variables are use, except for options, and they are ignored after reading a DXF drawing.

So it should work.

**Comment by BebeSparkelSparkel** [comment]
Ok thanks a lot!
