### ISSUE TITLE
Fill and Hatch

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mozman/dxfgrabber#8]
Does dxfgrabber read fills and hatches? If so, where can I find them?

**Comment by mozman** [comment]
dxfgrabber does not support hatches and fills, ezdxf supports the HATCH entity.

http://ezdxf.readthedocs.io/en/latest/entities.html#hatch

**Comment by BebeSparkelSparkel** [comment]
Thank you

**Comment by leolv131** [comment]
Ezdxf supports the creation of hatches, but does ezdxf support reading hatches?
