### ISSUE TITLE
Wrong source for polyline elevation ?

### ISSUE THREAD

**Issue by s-leger** [mozman/dxfgrabber#9]
according [polyline dxf - 2000](https://www.autodesk.com/techpubs/autocad/acad2000/dxf/polyline_dxf_06.htm)
elevation for a polyline is stored in code 30.

current code 10 is for APP: "dummy point where z is elevation" could also work under some conditions, however as x and y are always 0 why not store only the z into entity.elevation and doing so stay consistent with lwpolyline elevation data type ?

**Comment by mozman** [comment]
If it ain't broke, don't fix it.
